import { z } from 'zod';
import reactionFile from '@/src/data/market-event-reactions.json';
import { formatPercent } from '@/src/utils/format';
import { releaseTimingOf, type ReleaseTiming } from './release-timing';
import { thaiShortDayLabel } from './time';
import { marketEventKindSchema, type MarketEvent, type MarketEventKind } from './types';

/**
 * WHAT THE S&P 500 DID ON THE LAST FEW DAYS THIS RELEASE WAS PUBLISHED.
 *
 * ===========================================================================
 * THE ONE SENTENCE THIS MODULE IS ALLOWED TO WRITE
 * ===========================================================================
 *     ครั้งก่อน ๆ — S&P 500 วันนั้น: +0.42% / -1.10% / +0.20%
 *
 * A list of dates and what an index closed at, relative to the session before.
 * Every number was measured and can be checked against any chart. Nothing here
 * says the release caused any of them, because nothing in this codebase
 * computed that — no correlation, no event study, no control for the six other
 * things that happen on a Friday morning.
 *
 * The phrases that would cross that line are enumerated in
 * `EVENT_REACTION_MUST_NOT_SAY` with the reasoning, banned by eslint over this
 * folder, and asserted over rendered output. The subtle one is "เฉลี่ย": an
 * average of three release days is arithmetic anybody can do and reads as a
 * finding, because it implies the three are samples of one repeatable quantity.
 * They are three dates.
 *
 * ===========================================================================
 * A LIST NEVER MIXES TWO MEASUREMENTS
 * ===========================================================================
 * `market-event-reactions.json` keeps `beforeOpen`, `intraday` and
 * `afterClose` as separate arrays because a close-to-close change CONTAINS an
 * 8:30 a.m. release and does not contain a 2:00 p.m. one. This module reads the
 * single bucket the event itself belongs to and never looks in another, so a
 * list a reader is invited to compare down is always one quantity.
 *
 * Today that falls out per kind — every FOMC row is intraday, every other kind
 * is before the open — so the question would be moot even without the
 * separation. The separation is what keeps it moot when a release moves.
 *
 * ===========================================================================
 * NOTHING IS FETCHED, AND AN ABSENT NUMBER IS ABSENT
 * ===========================================================================
 * The file is static and generated by `scripts/backfill-event-reactions.ts`. A
 * close from a past session does not change, so re-deriving it per render would
 * be spending a provider call on a constant — and it would put a network
 * failure between a reader and a historical fact.
 *
 * When there is nothing to show this returns NULL rather than an empty view.
 * The caller renders nothing at all: a heading over a dash is a worse answer
 * than no heading, because it invites the reader to wonder what is broken. As
 * of today the file is empty for every event, so the block renders nowhere.
 */

const reactionRowSchema = z.object({
  eventId: z.string().min(1),
  kind: marketEventKindSchema,
  sessionDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/),
  previousSessionDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/),
  close: z.number().finite(),
  previousClose: z.number().finite(),
  changePercent: z.number().finite(),
});

const reactionFileSchema = z.object({
  schemaVersion: z.literal(1),
  benchmark: z.object({
    symbol: z.string().min(1),
    labelTh: z.string().min(1),
    measure: z.literal('close-to-close'),
  }),
  beforeOpen: z.array(reactionRowSchema),
  intraday: z.array(reactionRowSchema),
  afterClose: z.array(reactionRowSchema),
});

export type ReactionRow = z.infer<typeof reactionRowSchema>;

/*
 * A file that does not parse yields NO reactions, never a partial set — the
 * discipline `calendar.ts` states for the same reason. Half a history looks
 * exactly like a complete one and would quietly tell a reader that a release
 * has only ever been published twice.
 */
const parsed = reactionFileSchema.safeParse(reactionFile);

export const BENCHMARK_LABEL_TH = parsed.success ? parsed.data.benchmark.labelTh : 'S&P 500';

const BUCKETS: Record<ReleaseTiming, readonly ReactionRow[]> = {
  beforeOpen: parsed.success ? parsed.data.beforeOpen : [],
  intraday: parsed.success ? parsed.data.intraday : [],
  afterClose: parsed.success ? parsed.data.afterClose : [],
};

/** How many past publications a block names before it stops. */
export const REACTION_SAMPLE_LIMIT = 3;

export interface ReactionSample {
  /** The New York session, `YYYY-MM-DD`. */
  sessionDate: string;
  /** "11 ก.ย. 2569" — the date, so the row is checkable. */
  dayLabelTh: string;
  changePercent: number;
  /** "+0.42%" — signed, because a price change's sign is the whole point. */
  changeLabel: string;
  /** For colour only. Never the only channel: `changeLabel` carries the sign. */
  direction: 'up' | 'down' | 'flat';
}

export interface EventReactionView {
  eventId: string;
  kind: MarketEventKind;
  timing: ReleaseTiming;
  benchmarkLabelTh: string;
  /** "ครั้งก่อน ๆ" — states that these are earlier publications, nothing more. */
  headingTh: string;
  /** "S&P 500 วันนั้น" — what the numbers beside it are OF. */
  measureLabelTh: string;
  /** Most recent first. Never empty: an empty view is null instead. */
  samples: ReactionSample[];
}

export function reactionsFor(
  event: MarketEvent,
  {
    limit = REACTION_SAMPLE_LIMIT,
    buckets = BUCKETS,
  }: { limit?: number; buckets?: Record<ReleaseTiming, readonly ReactionRow[]> } = {},
): EventReactionView | null {
  const timing = releaseTimingOf(event.at);
  if (!timing) return null;

  const samples = buckets[timing]
    .filter((row) => row.kind === event.kind && row.eventId !== event.id)
    /*
     * Sorted here rather than trusted from the file. The generator writes rows
     * in calendar order, but "most recent first" is what the copy claims and a
     * view that silently depended on the writer's ordering would be wrong in
     * exactly the case somebody is debugging.
     */
    .sort((left, right) => (left.sessionDate < right.sessionDate ? 1 : left.sessionDate > right.sessionDate ? -1 : 0))
    .slice(0, Math.max(0, limit))
    .map(toSample);

  if (samples.length === 0) return null;

  return {
    eventId: event.id,
    kind: event.kind,
    timing,
    benchmarkLabelTh: BENCHMARK_LABEL_TH,
    headingTh: 'ครั้งก่อน ๆ',
    measureLabelTh: `${BENCHMARK_LABEL_TH} วันนั้น`,
    samples,
  };
}

function toSample(row: ReactionRow): ReactionSample {
  return {
    sessionDate: row.sessionDate,
    dayLabelTh: thaiShortDayLabel(row.sessionDate),
    changePercent: row.changePercent,
    changeLabel: formatPercent(row.changePercent),
    direction: row.changePercent > 0 ? 'up' : row.changePercent < 0 ? 'down' : 'flat',
  };
}

/**
 * The whole block as one line, for a caller that wants a sentence.
 *
 *     ครั้งก่อน ๆ — S&P 500 วันนั้น: +0.42% / -1.10% / +0.20%
 *
 * Exported so the wording exists in exactly one place. The component renders
 * the parts separately — it colours each number — and this is what the test
 * asserts the parts add up to, which is how the two stay the same sentence.
 */
export function reactionSentenceTh(view: EventReactionView): string {
  const numbers = view.samples.map((sample) => sample.changeLabel).join(' / ');
  return `${view.headingTh} — ${view.measureLabelTh}: ${numbers}`;
}
