export {
  INTERVAL_GROUP_LABEL,
  INTERVAL_OPTIONS,
  RANGE_OPTIONS,
  RANGE_SECTION_LABEL,
  canonicalInterval,
  canonicalRange,
  intervalOption,
  intervalsByGroup,
  isIntervalEnabled,
  isRangeEnabled,
  rangeOption,
  unsupportedReason,
  type IntervalGroup,
  type IntervalOption,
  type RangeOption,
} from './catalog';
export {
  chartCompatibleSelection,
  chartSupportedRanges,
  defaultIntervalForChartRange,
  isChartSelectionSupported,
  type ChartCompatibleSelection,
} from './compatibility';
export {
  CHART_PREFERENCES_STORAGE_KEY,
  DEFAULT_CHART_PREFERENCES,
  LEGACY_CHART_PREFERENCES_STORAGE_KEY,
  mergeChartPreferences,
  migrateLegacyChartPreferences,
  readChartPreferences,
  safeStorage,
  toggleFavoriteInterval,
  toggleFavoriteRange,
  writeChartPreferences,
  type ChartDisplayType,
  type ChartPreferences,
} from './preferences';
